version: "3.9"
services:
  redis:
    image: redis:alpine
    ports:
      - 6379
    restart: unless-stopped
  machineelf:
    build: .
    image: machineelf:latest
    volumes:
      - type: volume
        source: config
        target: /config
    environment:
      - CONFIG_FILE=/config/machineelf.json
    restart: unless-stopped
volumes:
  config:
