version: "3.9"
services:
  redis:
    image: redis:alpine
    ports:
      - 6379
    restart: unless-stopped
  sql:
    build: .docker/sql
    image: elfsql:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=passwd
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
  machineelf:
    build: .
    volumes:
      - type: volume
        source: config
        target: /config
    environment:
      - CONFIG_FILE=/config/machineelf.json
    restart: unless-stopped
volumes:
  config:
  pgdata:
