version: "3.9"
services:
  redis:
    image: redis:alpine
    ports:
      - 6379
    restart: unless-stopped
  sql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=passwd
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
      - type: bind
        source: .initdb/
        target: /docker-entrypoint-initdb.d/
  machineelf:
    build: .
    image: machineelf:latest
    volumes:
      - type: volume
        source: config
        target: /config
    environment:
      - CONFIG_FILE=/config/machineelf.json
    restart: unless-stopped
volumes:
  config:
  pgdata:
